WebApp/Controllers/OrderController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Utility;

namespace WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize]
        [HttpGet]
        public IActionResult Get(string? staus=null)
        {
            var orderList = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser");
            if (staus == "cancelled")
            {
                orderList = orderList.Where(u => u.Status == StaticDetail.StatusCancelled || u.Status == StaticDetail.StatusRejected);
            }
            else if(staus == "completed")
            {
                orderList = orderList.Where(u => u.Status == StaticDetail.StatusCompleted);
            }
            else if (staus == "ready")
            {
                orderList = orderList.Where(u => u.Status == StaticDetail.StatusReady);
            }
            else
            {
                orderList = orderList.Where(u => u.Status == StaticDetail.StatusInProccess || u.Status == StaticDetail.StatusSubmtted);
            }
            return Json(new { data = orderList });
        }

    }
}

WebApp/Pages/Admin/Order/ManageOrder.cshtml.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Models.ViewModel;
using Utility;

namespace WebApp.Pages.Admin.Order
{
    [Authorize(Roles = $"{StaticDetail.ManagerRole},{StaticDetail.KitchenRole}")]
    public class ManageOrderModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public List<OrderDetail_VM> orderDetailVM { get; set; }
        public ManageOrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet()
        {
            orderDetailVM = new();
            List<OrderHeader> orderHeader = _unitOfWork.OrderHeader.GetAll(u => u.Status == StaticDetail.StatusSubmtted ||
            u.Status == StaticDetail.StatusInProccess).ToList();

            foreach (OrderHeader item in orderHeader)
            {
                OrderDetail_VM individual = new OrderDetail_VM()
                {
                    orderHeader = item,
                    OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderId == item.Id).ToList()
                };
                orderDetailVM.Add(individual);
            }
        }
        public IActionResult OnPostOrderInProccess(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetail.StatusInProccess);
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }

        public IActionResult OnPostOrderReady(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetail.StatusReady);
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }

        public IActionResult OnPostOrderCancel(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetail.StatusCancelled);
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }
    }
}

WebApp/Pages/Admin/Order/OrderDetails.cshtml.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Models.ViewModel;
using Stripe;
using Utility;

namespace WebApp.Pages.Admin.Order
{
    public class OrderDetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public OrderDetail_VM orderDetail_VM { get; set; }
        public OrderDetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet(int id)
        {
            orderDetail_VM = new()
            {
                orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id, includeProperties: "ApplicationUser"),
                OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderId == id).ToList()
            };
        }
        public IActionResult OnPostOrderCompleted(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetail.StatusCompleted);
            _unitOfWork.Save();
            return RedirectToPage("OrderList");
        }
        public IActionResult OnPostOrderRefund(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == orderId);
            var option = new RefundCreateOptions
            {
                Reason = RefundReasons.RequestedByCustomer,
                PaymentIntent = orderHeader.PaymentIntentId
            };

            var service = new RefundService();
            Refund refund = service.Create(option);

            _unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetail.StatusRefunded);
            _unitOfWork.Save();
            return RedirectToPage("OrderList");
        }


        public IActionResult OnPostOrderCancel(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetail.StatusCancelled);
            _unitOfWork.Save();
            return RedirectToPage("OrderList");
        }
    }
}

WebApp/Pages/Admin/Order/OrderList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Admin.Order
{
    [Authorize]
    public class OrderListModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApp/Pages/Admin/Order/ManageOrder.cshtml
@page
@model WebApp.Pages.Admin.Order.ManageOrderModel
@using Utility



<h1 class="text-primary py-3">Manage Order</h1>
<form method="post">
    <div class="container row bg-white p-2 mb-3 rounded">
        @foreach (var item in @Model.orderDetailVM)
        {
            <div class="col-12 pb-3 pt-3 mt-4 border  rounded">
                <div class="row">
                    <div class="col-4">
                        Order Number : @item.orderHeader.Id
                        <ul class="text-info">
                            @foreach (var details in item.OrderDetails)
                            {
                                <li>@details.Name x @details.Count</li>
                            }
                        </ul>
                    </div>
                    <div class="col-4 pb-2">
                        <div class="input-group pb-2">
                            <div class="input-group-append">
                                <span class="input-group-text bg-secondary border">Time</span>
                            </div>
                            <input type="text" value="@item.orderHeader.PickUpTime" class="form-control" readonly />
                        </div>
                        <textarea asp-for="@item.orderHeader.Comments" placeholder="comment" readonly class="rounded border form-control" rows="3"></textarea>
                    </div>
                    <div class="col-3 offset-1 d-flex align-content-center">
                        <div class="col-12">

                            @if (item.orderHeader.Status == StaticDetail.StatusSubmtted)
                            {
                                <button type="submit" class="btn btn-primary form-control mb-3"
                                asp-page-handler="OrderInProccess" asp-route-orderId="@item.orderHeader.Id">
                                    <i class="bi bi-check-square"></i> &nbsp; Start Cooking
                                </button>
                            }
                            @if (item.orderHeader.Status == StaticDetail.StatusInProccess)
                            {
                                <button type="submit" class="btn btn-success form-control mb-3"
                                asp-page-handler="OrderReady" asp-route-orderId="@item.orderHeader.Id">
                                    <i class="bi bi-emoji-laughing"></i> &nbsp; Order Ready
                                </button>
                            }
                            <button type="submit" class="btn btn-warning form-control mb-3"
                            asp-page-handler="OrderCancel" asp-route-orderId="@item.orderHeader.Id">
                                <i class="bi bi-x-square-fill"></i> &nbsp; Cancel Order
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

</form>

WebApp/Pages/Admin/Order/OrderDetails.cshtml
@page
@model WebApp.Pages.Admin.Order.OrderDetailsModel
@using Utility

<form method="post">
    <div class="border p-4 ml-1 backgroundWhite mt-4">
        <div class="row pb-1">
            <div class="col-12 col-md-6 ">
                <p class="h2  text-primary">Order Details</p>
            </div>
            <div class="col-12 col-md-4 offset-md-2">
                <a asp-page="/Admin/Order/OrderList" class="btn btn-outline-primary form-control">Back to Orders </a>
            </div>
        </div>
        <hr />

        <div class="row pt-2">

            <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
              
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Name
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetail_VM.orderHeader.PickupName" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                       Email
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetail_VM.orderHeader.ApplicationUser.Email" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Phone Number
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetail_VM.orderHeader.PhoneNumber" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                       Order Total
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetail_VM.orderHeader.OrderTotal" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Order Date Time
                    </div>
                    <div class="col-md-9 col-12">
                        <input value="@Model.orderDetail_VM.orderHeader.PickUpDate.ToShortDateString() @Model.orderDetail_VM.orderHeader.PickUpTime.ToShortTimeString()"  disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Comments
                    </div>
                    <div class="col-md-9 col-12">
                        <textarea asp-for="orderDetail_VM.orderHeader.Comments" disabled class="form-control" rows="3" ></textarea>
                    </div>
                </div>

            </div>

            <div class="col-lg-4 col-12">
                <button type="submit" disabled class="btn btn-outline-info form-control">@Model.orderDetail_VM.orderHeader.Status</button>
                <h4 class="d-flex justify-content-between align-content-center mb-3 pt-3">
                    <span class="text-muted">Order ID: </span>
                    <span class="badge badge-secondary badge-pill">@Model.orderDetail_VM.orderHeader.Id</span>
                </h4>
                <ul class="list-group mb-3">
                    @foreach (var item in @Model.orderDetail_VM.OrderDetails)
                    {
                        <li class="list-group-item d-flex justify-content-between">
                            <div>
                                <h6 class="my-0">@item.Name</h6>
                                <small class="text-muted">Quantity : @item.Count</small>
                            </div>
                            <span class="text-muted">$@(item.Price*item.Count)</span>
                        </li>
                    }

                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <span class="text-info"> Total (USD)</span>
                        <strong class="text-info">$@Model.orderDetail_VM.orderHeader.OrderTotal</strong>
                    </li>

                </ul>
                
                    <div class="row pt-3">
                        @if(Model.orderDetail_VM.orderHeader.Status == StaticDetail.StatusReady
                        && (User.IsInRole(StaticDetail.ManagerRole) || User.IsInRole(StaticDetail.FrontDeskRole)))
                        {
                            <div class="col-12 pb-2">
                                <button type="submit" class="btn btn-primary form-control"
                                asp-page-handler="OrderCompleted" asp-route-orderId="@Model.orderDetail_VM.orderHeader.Id">
                                Complete Order</button>
                            </div>
                        }
                        @if ((Model.orderDetail_VM.orderHeader.Status == StaticDetail.StatusInProccess
                        || Model.orderDetail_VM.orderHeader.Status == StaticDetail.StatusSubmtted
                        || Model.orderDetail_VM.orderHeader.Status == StaticDetail.StatusReady)
                        && (User.IsInRole(StaticDetail.ManagerRole) || User.IsInRole(StaticDetail.FrontDeskRole)))
                    {
                        <div class="col-6">
                            <button type="submit" class="btn btn-warning form-control"
                            asp-page-handler="OrderCancel" asp-route-orderId="@Model.orderDetail_VM.orderHeader.Id">
                                <i class="bi bi-x-square"></i> Cancel Order</button>
                        </div>
                        <div class="col-6">
                            <button type="submit" class="btn btn-danger form-control"
                            asp-page-handler="OrderRefund" asp-route-orderId="@Model.orderDetail_VM.orderHeader.Id">
                                <i class="bi bi-currency-dollar"></i> Refund Order</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</form>

WebApp/Pages/Admin/Order/OrderList.cshtml
@page
@model WebApp.Pages.Admin.Order.OrderListModel

@{
    var status = HttpContext.Request.Query["status"];
    var cancelled = "text-primary";
    var inproccess= "text-primary";
    var completed= "text-primary";
    var ready= "text-primary";

    if(status == "cancelled")
    {
        cancelled = "active  text-white";
    }else if(status == "ready")
    {
        ready = "active  text-white";
    }else if(status == "completed")
    {
        completed = "active  text-white";
    }else
    {
        inproccess = "active  text-white";
    }
}

<div class="container p-3">
    <div class="d-flex justify-content-between">
        <div class="p2">
            <h2 class="text-primary"> Order List</h2>
        </div>
        <div class="p-2">
            <ul class="list-group list-group-horizontal-sm">
                <a style="text-decoration:none;" asp-page="OrderList"
                asp-route-status="cancelled">
                <li class="list-group-item @cancelled">Cancelled</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList"
                asp-route-status="completed">
                <li class="list-group-item @completed">Completed</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList"
                asp-route-status="ready">
                <li class="list-group-item @ready">Ready For Pickup</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList"
                asp-route-status="inproccess">
                <li class="list-group-item @inproccess">In Proccess</li>
                </a>
            </ul>
        </div>
    </div>
    </br>
    
    <table id="orderList_load" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Order Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Order Toatal</th>
                <th>Pickup Time</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script type="text/javascript" src="~/js/orderList.js"></script>
}